### ISSUE TITLE
Error: undefined is not an object (evaluating 'EventPluginHub.injection') on react-dom@16.5.0

### ISSUE THREAD

**Issue by jeremygrant** [necolas/react-native-web#1096]
Hi guys,

I just ran into this problem and thought I'd let you know. I'll try and dig into it a little more, but just in case someone else runs into it or wants to pick it up

**The problem**

React Native Web doesn't work with `react-dom@16.5.0`

It seems that React DOM has removed some functionality that React Native Web requires

```
undefined is not an object (evaluating 'EventPluginHub.injection')
```

Which is likely due to https://github.com/facebook/react/pull/13539 causing it to fail here https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/createElement/index.js#L17-L21

**How to reproduce**

https://codesandbox.io/s/542j6l8m8x

**Expected behavior**

That it all looks pretty

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.8.*`
* React (version): `16.5.0`
* Browser: `Any`

Cheers,
Jeremy

**Comment by necolas** [comment]
Thanks

**Comment by necolas** [comment]
Waiting for React to put out a patch release reintroducing the API. RNW 0.9.0 will be compatible with React 16.5.x

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/13598 is in 16.5.1.
So this should fix it: https://github.com/facebook/react/pull/13598.

**Comment by vladp** [comment]
Using RNW 0.8.10 and RN  16.5.1  -- still not working for me. Same error

I also checked that in my node_module/react  I have the 16.5.1 package.json -- and I do.
setting react, react-dom, react-art to **16.4.2**  fixes, the problem in the mean time, for me.



my package json:

```


{
  "name": "wrnw-csr-cra",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^3.3.7",
    "compression": "^1.7.3",
    "hi-base32": "^0.5.0",
    "immutable": "3.8.2",
    "lodash": "^4.17.10",
    "prop-types": "^15.6.2",
    "pubsub-js": "^1.6.1",
    "react": "^16.5.1",
    "react-art": "^16.5.1",
    "react-bootstrap": "^0.32.4",
    "react-dom": "^16.5.1",
    "react-dropzone-component": "^3.2.0",
    "react-native-vector-icons": "^5.0",
    "react-native-web": "^0.8.10",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.5",
    "resize-observer-polyfill": "^1.5.0",
    "tree-model": "^1.0.7",
    "url-search-params-polyfill": "^4.0.0"
  },
  "scripts": {
    "analyze": "source-map-explorer build/static/js/main.*",
    "flow": "$(npm bin)/flow",
    "flow start": "$(npm bin)/flow start",
    "flow stop": "$(npm bin)/flow stop",
    "flow status": "$(npm bin)/flow status",
    "flow coverage": "$(npm bin)/flow coverage",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "ostart": "react-app-rewired start",
    "obuild": "react-app-rewired build",
    "otest": "react-app-rewired test --env=jsdom",
    "postinstall": "$(npm bin)/flow-typed install"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.5.0",
    "eslint-config-react-native": "^3.0.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.2.1",
    "flow-bin": "^0.80",
    "flow-typed": "^2.5.1",
    "jest": "^23.5.0",
    "jest-cli": "^23.5.0",
    "react-app-rewired": "^1.6.2",
    "source-map-explorer": "^1.6.0",
    "treeify": "^1.1.0",
    "webpack-merge": "^4.1.4"
  }
}

```
The error stack trace


<img width="1152" alt="react-16 5 1-showstopper-rnw" src="https://user-images.githubusercontent.com/94890/45582530-c2998b00-b87f-11e8-94b4-3ae398d0e441.png">

**Comment by vladp** [comment]
@gaearon , thank you.  It seems I misunderstood the relations of what was being closed/fixed and where.

**Comment by stevensacks** [comment]
@necolas Do you have an ETA on this fix?

**Comment by sync** [comment]
there is a PR open: https://github.com/necolas/react-native-web/pull/1106
